/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1dNMfJlUs31
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { useState } from "react";
import { Button } from "./ui/button"
import { Input } from "./ui/input"

export function AuthenticatedPage({user, logout, onSubmit}: any) {
  const [flavor, setFlavor] = useState("");

  return (
    <div className="flex h-screen w-full items-center justify-center bg-gradient-to-br from-[#7e22ce] to-[#a855f7]">
      <div className="rounded-lg bg-white p-8 shadow-lg w-full max-w-md">
        <div className="flex items-center justify-between mb-6">
          <div className="bg-gray-100 px-3 py-1 rounded-full text-sm text-gray-500">hi {user?.email}</div>
          <Button onClick={logout}>Sign Out</Button>
        </div>
        <div className="space-y-4">
          <h2 className="text-2xl font-bold">Whats your favorite ice cream flavor?</h2>
          <div className="flex items-center space-x-4">
            <Input className="flex-1" onChange={(e) => {setFlavor(e.target.value)}} placeholder="Enter your favorite flavor" type="text" />
            <Button onClick={()=> {
              onSubmit(flavor);
              setFlavor("");
            }}>Submit</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
