/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NJbIUxapyU3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { useEffect, useState } from "react";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function BurnBookComponent() {
  const [burns, setBurns] = useState([{name: "", burn: "", image: ""}]);

  useEffect(() => {
    // setBurns([
    //   {
    //     name: "Cady Heron",
    //     description: "Totally weird and gross. Trying way too hard to be cool.",
    //     image: "/placeholder.svg",
    //   },
    //   {
    //     name: "Regina George",
    //     description: "Ugly, poor, and a total bitch. Thinks she's so hot.",
    //     image: ""
    //   },
    //   {
    //     name: "Gretchen Wieners",
    //     description: "Desperate for attention. Tries too hard to be Regina's friend.",
    //     image: ""
    //   },
    //   {
    //     name: "Karen Smith",
    //     description: "Dumb as a box of rocks. Can't even tie her own shoes.",
    //     image: ""
    //   }
    // ])
    async function fetchDecryptedData() {
      const response = await fetch("/api/bring-back-fetch", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          // "Authorization": `Bearer ${getToken()}`,
        }
      });
      const data = await response.json();
      console.log(data);
      setBurns(data);
    }

    fetchDecryptedData();
  }, [])

  return (
    <div className="bg-[#ff69b4] ">
    <div className="w-full max-w-md mx-auto">
      <div className="rounded-lg shadow-lg p-8">
        <h1 className="text-4xl font-cursive text-center mb-6 text-white">Burn Book 💅</h1>
        <div className="space-y-8">
          {burns.map(burn => (
            <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-2xl font-ransom mb-4">{burn.name}</h2>
            <p className="text-sm font-ransom mb-2">{burn.burn}</p>
            <div className="flex justify-end">
              <img
                alt="Doodle"
                className="w-20 h-20"
                height="80"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "80/80",
                  objectFit: "cover",
                }}
                width="80"
              />
            </div>
            </div>
          ))}
        </div>
      </div>
    </div>
    </div>
  )
}
